[package]
name = "logo"
version = "0.1.0"
authors = ["isandrk"]
#autobins = false # TODO: Remove.

#[[bin]]
#name = "evaluator"
#path = "src/evaluator.rs"

[dependencies]
ggez = "0.9"
scopeguard = "1.2.0"
